<a href="https://colab.research.google.com/github/leemijung/AI_Basic/blob/main/zero_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이토치 기초

In [ ]:
import torch

In [ ]:
def print_val(x):
    print "Type: ", type(x)
    print "Shape: ", x.shape
    print "값:\n", x
    print " "

In [ ]:
x=torch.rand(2, 3, 2) #uniform: 0~1사이 모든 값들이 나올 확률이 같다
print_val(x)

x=torch.randn(2, 3) #Gaussian: 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값
print_val(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3, 2])
값:
tensor([[[0.0756, 0.2796],
         [0.1422, 0.3581],
         [0.5746, 0.9492]],

        [[0.8422, 0.7980],
         [0.7364, 0.5117],
         [0.1969, 0.5532]]])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
값:
tensor([[-0.4844,  0.2882,  0.3943],
        [-1.0233,  0.7451,  0.4395]])
 


In [ ]:
x=torch.randperm(4) #0~n-1(4-1)까지 값을 원소로 갖는 배열 -> 랜덤 배열
print_val(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([4])
값:
tensor([1, 0, 3, 2])
 


In [ ]:
#[start, end]구간을 step 단위로 나눠서 배열로 생성
x=torch.arange(0, 3, step=0.5)
print_val(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([6])
값:
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
 


In [ ]:
print_val(torch.ones(3, 4)) #1로 채워진 배열 생성
print_val(torch.zeros(3, 4)) #0으로 채워진 배열 생성

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([3, 4])
값:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([3, 4])
값:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
 


In [ ]:
print_val(torch.Tensor(2, 4)) #쓰레기값으로 채워진 배열 생성

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 4])
값:
tensor([[-8.0528e-08,  3.0875e-41, -8.0528e-08,  3.0875e-41],
        [-8.0528e-08,  3.0875e-41,  1.4013e-45,  0.0000e+00]])
 


In [ ]:
print_val(torch.Tensor([2, 3])) #Tensor이지만, [ , ]로 값 지정 가능하다
print_val(torch.Tensor([[2, 3], [3, 4]]))

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2])
값:
tensor([2., 3.])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 2])
값:
tensor([[2., 3.],
        [3., 4.]])
 


In [ ]:
#Tensor 타입 변환
x=torch.FloatTensor(2, 3)
print_val(x)

x=x.type_as(torch.IntTensor())
print_val(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
값:
tensor([[ 1.1260e-31,  4.5810e-41,  1.1260e-31],
        [ 4.5810e-41, -2.2446e+29,  4.5808e-41]])
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
값:
tensor([[          0,           0,           0],
        [          0, -2147483648,           0]], dtype=torch.int32)
 


In [ ]:
#Tensor 크기 변환
torch.FloatTensor(3, 4, 5).size()

torch.Size([3, 4, 5])

In [ ]:
# numpy array -> torch tensor
import numpy as np
np_x=np.ndarray((2, 3), dtype=int)
print_val(np_x)

x=torch.from_numpy(np_x)
print_val(x)

Type:  <type 'numpy.ndarray'>
Shape:  (2, 3)
값:
[[              0               0               0]
 [              0               0 140402480906240]]
 
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
값:
tensor([[              0,               0,               0],
        [              0,               0, 140402480906240]])
 
